name: Node.js CI
on: [repository_dispatch]

permissions:
  contents: read
  pages: write
  id-token: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with: 
        repository: ${{ github.event.client_payload.repository }}
    - uses: actions/setup-node@v2
      with:
        node-version: "16"
        cache: "npm"
    - name: Build & Generate Static Site for prod
      run: |
        npm install 
        npm run build
    - name: Setup Pages
      uses: actions/configure-pages@v1
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: "build"
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@main
      env:
        GITHUB_TOKEN: ${{ secrets.SAML_GITHUB_TOKEN }}
